general:
  buildTool: mta
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'apm'
      space: 'nova'
      credentialsId: 'CF_CREDENTIALSID'